server:
  port: 8081

spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5433/HealthyDiat_user_db
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
